### ISSUE TITLE
Update Android Things support library version to `1.0`

### ISSUE THREAD

**Issue by Fleker** [wintersandroid/Android-Things-RF24#1]

**Comment by mwinters-stuff** [comment]
Hi.
I thought I had, maybe it is in progress on my desktop and then I would have gotten distracted (months ago).

I will look at it later today.

**Comment by mwinters-stuff** [comment]
Done, looks like I did it and then didnt commit. Also submitted to androidthings.withgoogle.com (also did the pca9685 driver).
